// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFuqUSjGUizqd06Piq4_fztDBCzHIePw',
    appId: '1:886244958612:web:92355d7b3687368a82af81',
    messagingSenderId: '886244958612',
    projectId: 'sakina-d27f3',
    authDomain: 'sakina-d27f3.firebaseapp.com',
    storageBucket: 'sakina-d27f3.firebasestorage.app',
    measurementId: 'G-6EGTG5PDPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UMlP8aFRo6tOlocT48RCjTSiA92xQ3c',
    appId: '1:886244958612:android:a3154ee6dbb2404082af81',
    messagingSenderId: '886244958612',
    projectId: 'sakina-d27f3',
    storageBucket: 'sakina-d27f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXrWxB0OrH971OT7tktVjP5v_iWf0nRs',
    appId: '1:886244958612:ios:fb88025f6bac474882af81',
    messagingSenderId: '886244958612',
    projectId: 'sakina-d27f3',
    storageBucket: 'sakina-d27f3.firebasestorage.app',
    iosBundleId: 'com.example.sakina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXrWxB0OrH971OT7tktVjP5v_iWf0nRs',
    appId: '1:886244958612:ios:fb88025f6bac474882af81',
    messagingSenderId: '886244958612',
    projectId: 'sakina-d27f3',
    storageBucket: 'sakina-d27f3.firebasestorage.app',
    iosBundleId: 'com.example.sakina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGFuqUSjGUizqd06Piq4_fztDBCzHIePw',
    appId: '1:886244958612:web:9454b433c9ae843c82af81',
    messagingSenderId: '886244958612',
    projectId: 'sakina-d27f3',
    authDomain: 'sakina-d27f3.firebaseapp.com',
    storageBucket: 'sakina-d27f3.firebasestorage.app',
    measurementId: 'G-94H6VQG44Q',
  );

}